### ISSUE TITLE
Basic components - V0.0.2

### ISSUE THREAD

**Issue by shahryarjb** [mishka-group/mishka_chelekom#8]
- [x] #78
- [x] #23 
- [x] #22 
- [x] #21 
- [x] #66 
- [x] #65 
- [x] #9 
- [x] #56
- [x] #50   
- [x] #12 
- [x] #25 
- [x] #69 
- [x] #68 
- [x] #67 
- [x] #64 
- [x] #59 
- [x] #55 
- [x] #48 
- [x] #39 
- [x] #37 
- [x] #34 
- [x] #31 
- [x] #30 
- [x] #19 
- [x] #11 
- [x] #6 
- [x] #49 
- [x] #47 
- [x] #45
- [x] #182 

---

### Dark mode and new Colors

- [x] Add dark mode and fix issues of gradient variants of Button component [#91](https://github.com/mishka-group/mishka_chelekom/pull/91)
- [x] Add dark mode and fix issues of gradient variants of Badge component [#94](https://github.com/mishka-group/mishka_chelekom/pull/94)
- [x] Add dark mode and fix issues of Overlay of Drawer component [#96](https://github.com/mishka-group/mishka_chelekom/pull/96)
- [x] Add dark mode of Divider component [#97](https://github.com/mishka-group/mishka_chelekom/pull/97)
- [x] Add dark mode of Avatar component [#98](https://github.com/mishka-group/mishka_chelekom/pull/98)
- [x] Add dark mode of Alert component [#99](https://github.com/mishka-group/mishka_chelekom/pull/99)
- [x] Add dark mode of Spinner component [#100](https://github.com/mishka-group/mishka_chelekom/pull/100)
- [x] Add dark mode of Banner component [#101](https://github.com/mishka-group/mishka_chelekom/pull/101)
- [x] Add dark mode of Breadcrumb component [#102](https://github.com/mishka-group/mishka_chelekom/pull/102)
- [x] Add dark mode of Blockquote component [#103](https://github.com/mishka-group/mishka_chelekom/pull/103)
- [x] Add dark mode of Dropdown component [#104](https://github.com/mishka-group/mishka_chelekom/pull/104)
- [x] Add dark mode of Overlay component [#106](https://github.com/mishka-group/mishka_chelekom/pull/106)
- [x] Add dark mode of Card component [#107](https://github.com/mishka-group/mishka_chelekom/pull/107)
- [x] Add dark mode and add `show_arrow` prop of Popover component [#121](https://github.com/mishka-group/mishka_chelekom/pull/121)
- [x] Add dark mode of Rating component [#123](https://github.com/mishka-group/mishka_chelekom/pull/123)
- [x] Add dark mode of Chat component [#125](https://github.com/mishka-group/mishka_chelekom/pull/125)
- [x] Add dark mode of Modal component [#126](https://github.com/mishka-group/mishka_chelekom/pull/126)
- [x] Add dark mode of Keyboard component [#127](https://github.com/mishka-group/mishka_chelekom/pull/127)
- [x] Add dark mode of Jumbotron component [#128](https://github.com/mishka-group/mishka_chelekom/pull/128)
- [x] Add dark mode of Indicator component [#129](https://github.com/mishka-group/mishka_chelekom/pull/129)
- [x] Add dark mode of Carousel component [#130](https://github.com/mishka-group/mishka_chelekom/pull/130)
- [x] Add dark mode of Footer component [#132](https://github.com/mishka-group/mishka_chelekom/pull/132)
- [x] Add dark mode of MegaMenu component [#133](https://github.com/mishka-group/mishka_chelekom/pull/133)
- [x] Add dark mode of Navbar component [#134](https://github.com/mishka-group/mishka_chelekom/pull/134)
- [x] Add dark mode of Progress component [#136](https://github.com/mishka-group/mishka_chelekom/pull/136)
- [x] Add dark mode of email, url, search, number, password, textarea, tel, text fields components [#138](https://github.com/mishka-group/mishka_chelekom/pull/138)
- [x] Add dark mode of FormWrapper component [#140](https://github.com/mishka-group/mishka_chelekom/pull/140)
- [x] Add dark mode of RadioField component [#143](https://github.com/mishka-group/mishka_chelekom/pull/143)
- [x] Add dark mode of CheckboxField component [#144](https://github.com/mishka-group/mishka_chelekom/pull/144)
- [x] Add dark mode of Sidebar component [#145](https://github.com/mishka-group/mishka_chelekom/pull/145)
- [x] Add dark mode of DateTimeField component [#146](https://github.com/mishka-group/mishka_chelekom/pull/146)
- [x] Add dark mode of Tooltip component [#147](https://github.com/mishka-group/mishka_chelekom/pull/147)
- [x] Add dark mode of Video component [#148](https://github.com/mishka-group/mishka_chelekom/pull/148)
- [x] Add dark mode of Typography component [#149](https://github.com/mishka-group/mishka_chelekom/pull/149)
- [x] Add dark mode of ToggleField component [#150](https://github.com/mishka-group/mishka_chelekom/pull/150)
- [x] Add dark mode of SpeedDial component [#151](https://github.com/mishka-group/mishka_chelekom/pull/151)
- [x] Add dark mode of Skeleton component [#152](https://github.com/mishka-group/mishka_chelekom/pull/152)
- [x] Add dark mode of TableOfContent component [#153](https://github.com/mishka-group/mishka_chelekom/pull/153)
- [x] Add dark mode of Timeline component [#154](https://github.com/mishka-group/mishka_chelekom/pull/154)
- [x] Add dark mode of Table component [#155](https://github.com/mishka-group/mishka_chelekom/pull/155)
- [x] Add dark mode of Tabs component [#156](https://github.com/mishka-group/mishka_chelekom/pull/156)
- [x] Add dark mode of NativeSelect component [#158](https://github.com/mishka-group/mishka_chelekom/pull/158)
- [x] Add dark mode of RangeField component [#159](https://github.com/mishka-group/mishka_chelekom/pull/159)
- [x] Add dark mode of Toast component [#160](https://github.com/mishka-group/mishka_chelekom/pull/160)
- [x] Add dark mode of List component [#161](https://github.com/mishka-group/mishka_chelekom/pull/161)
- [x] Add dark mode of Fieldset component [#162](https://github.com/mishka-group/mishka_chelekom/pull/162)
- [x] Add dark mode of FileField component [#163](https://github.com/mishka-group/mishka_chelekom/pull/163)
- [x] Add dark mode of Stepper component [#165](https://github.com/mishka-group/mishka_chelekom/pull/165)
- [x] Add dark mode of Accordion component [#166](https://github.com/mishka-group/mishka_chelekom/pull/166)
- [x] Add dark mode of DeviceMockup component [#167](https://github.com/mishka-group/mishka_chelekom/pull/167)
- [x] Add dark mode of pagination component [#168](https://github.com/mishka-group/mishka_chelekom/pull/168)
